language: node_js
node_js:
- 8.11.1
- lts/*
- 10.15.2
- node
cache: yarn
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s --
- export PATH="$HOME/.yarn/bin:$PATH"
install:
- npm install -g codecov
- NG_CLI_ANALYTICS=false npm install -g @angular/cli
- yarn install --frozen-lockfile
script:
- yarn --version
- yarn build
after_success:
- yarn --version
deploy:
  provider: npm
  email: sateeshkumar.m@gmail.com
  api_key:
    secure: Fbf0XultpFv4cCBlWYJMHadQb3UzvrgOnij6iQoXFmywWWUUuWeb1fyT3HYhgtGhl0oUi5ilG1M2ZYtr/QfPRrCcakXNUAlOiKGpHmdzK4TNDUBTzuAm+WXlGN4kZMfEikJO3pVbjzdjrbZmgb0dCJp7YGq4pRIYN8xo6CERiA38viyLUui6otALg9lrg10YOabMYiRgfwA31AHOhbI1tfVWCrAN401xOwb3hFrxOwz3jQV1t0dnFdPqiHwbxKoLyVI9nq84+q5Uaj8zeAylIt1IkVUkjUMxJof9PeZWRGM2PJOAKggHBNZS7Vr/YF20IqJzQdpIGiWCGT8QmKYWPvoZKe2acWocE9PnW6+HVYM/bovGHZKpJxtVKPHa4BIRIyOia0QHxHkanDcr2XcuPXcEwd1E6ASOJJjR67CaSEzd0cSA6FjcMasGqq+ObUPWC8gUKa16LwNqovahXAddrVesxK3vVITLTpAyoHvBLXZtlQSHEW1hqn/0p4a8hbd8nPz0emy3G5AVdw3u1q0ppiI98nBHBZ0IjeI5vPu6/0Grnzf9/3Vuk0do71fVoLBYJg/+Zf/z0wdHqQIyRMWUveOKHfcJvQ7fJTc9k1QrpVsSkwYi/grELrZ5gDmvQDLCH2k7/vsFCOLS7sTHSVwxUGoW2l01jyUMhY9fYgey+iI=
  on:
    tags: true
    repo: hmcts/nodejs-release-spike
  skip_cleanup: true
