language: node_js
node_js:
- 8.11.1
cache: yarn
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s --
- export PATH="$HOME/.yarn/bin:$PATH"
install:
- npm install -g codecov
- NG_CLI_ANALYTICS=false npm install -g @angular/cli
- yarn install --frozen-lockfile
script:
- yarn --version
- yarn build
after_success:
- yarn --version
- git config --global user.email "sateeshkumar.m@gmail.com"
- git config --global user.name "smathangi"
- git remote add upstream "https://${GH_TOKEN}@github.com/covfefe-spikes/nodejs-release-spike.git"
- export GIT_TAG=$(jq -r ".name" package.json)
- git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
- git push origin $GIT_TAG
deploy:
  provider: npm
  email: sateeshkumar.m@gmail.com
  api_key:
    secure: GltERxR3MbT5BkkP/hrj2V81TUHUHwb7nHYNXe3aAO18ic7V7wmxf/20CPREjprIe8gVEy/MTC7hpZcmHRSgOCc2W8C/VlO5KyjzkDjmPUioVcKdVSizF5yN0zHdpo+2RVH5NiAo8Xy3UISVAcpn/9P0o5zsf3c5AbLeaCt979Jf3vEydyL2TthS0TH9tLuWSsiepYN+MJt/2+1C1w0fQBpAbAXmDkyPQApaENxQz+XvhnyJNFdBs67tVoryvaFd33HfIaBr8T6uwJPxMV9NFG/xubwEgDkdNwYFAvSZs/KXPcjBiPpBU2uhKZsTXPCNKd9rDQ+U3i8rX//0zxf04eyN717V+1+lQ9u9j0h3Pt6tFQ3DDRyxEwICV0ehLt+WSMdd67F78u7885DPkNeqQEVuhyEwInkP0XUzVy1rJrmfMoFoq2zGRFKsaOKXdiXsudLkUpHx3BOT+vEzXfZFgb7yn0yQBXRRxw20QexKQFMd6CAjcwJSbGkkdBAghNt72EMEPVYqGo+BeoSjlJgyYR//ymjduDtLDo2Nlxq/NGfo1+U9HRJpPMngClN8DrV4zVqkMwiVxSPonr6bHVtLxVUXZnEgrlgIXIxfKB3z8bNNIdLPPMOnBQ86qcoEmxI5pzQ+jNiq49ro050596qiNS342FG7Kl5harmNhqVOYtc=
  on:
    tags: true
    repo: covfefe-spikes/nodejs-release-spike
  skip_cleanup: true
