language: node_js
node_js:
- 8.11.1
- lts/*
- 10.15.2
- node
cache: yarn
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s --
- export PATH="$HOME/.yarn/bin:$PATH"
install:
- npm install -g codecov
- NG_CLI_ANALYTICS=false npm install -g @angular/cli
- yarn install --frozen-lockfile
script:
- yarn --version
- yarn build
after_success:
- yarn --version
deploy:
  provider: npm
  email: sateeshkumar.m@gmail.com
  api_key:
    secure: XvZhV7JXUTqY9fP1eom+ChPxZkjknF2OFGlyCMsHv1uLw7/zPE8R/i5OQGfxMvYFumzypg+hBQ2HoKXiUxpX5/i0IMPSs6S4J93DnuJjjdU+02sJHHSTBlHhbj6Wg0izgGIzkSs7JDUXG758JNH8Wqn/Lb9TO1mtR9UDh4p5ZypizGFh1sk1uVqASaBdKmbjbR8KO3HCcH3KVYfDo+SFtm/xGP+tkMDnVkvyLUkF81Do1IJpM00wlqomKZgaYk36iIXeCrSWAKcAAGhRCbhKXRWQj8nBfP9j684Zi19c5GMcHEn1VyzgTK00C8I14HXXNxMj9g2Cyv/wIdT4jQAm6F6Ed8xZw9HsL2dX5zqKU6o8BZBjO6Sy+jgMjq9dFe849WSvnhpduhDRD2vUb6bcBA565cXvcgrWliRaEcLa8462ai7IZ88hpl6bxkFHxMvmvnAYUkED5WaGvWYNyYEenaJXqx6TXwaHf+nsI92UoVnRnSTk6hnTafFdIeujgjCvaouPhe2T2dWqkO2AzhVZq99WlKUMOh0UuPUlYi17W/NhUsa9YHY5skkW3J0urPIqgyX9wC+/vAI0h2VLzvZCL1aLqjdHeF5JDXRIJ1oqWsL0OKdemSpIgb4pFX4mgsSRXCpWfrPZqxOkhEUPP8e/Ko3c+U3BCPLfMrU/cRuezbQ=
  on:
    tags: true
    repo: hmcts/nodejs-release-spike
  skip_cleanup: true
