language: node_js
node_js:
- 8.11.1
cache: yarn
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s --
- export PATH="$HOME/.yarn/bin:$PATH"
install:
- npm install -g codecov
- NG_CLI_ANALYTICS=false npm install -g @angular/cli
- yarn install --frozen-lockfile
script:
- yarn --version
- yarn build
after_success:
- '[ "$TRAVIS_BRANCH" = "master" -o "$TRAVIS_PULL_REQUEST" = "true" ] && ./create-release-tag.sh'
before_deploy:
- if [[ "$TRAVIS_TAG" == *"-prerelease" ]]; then export PRERELEASE=true; else export PRERELEASE=false; fi
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: "RELEASE-NOTES.md"
  prerelease: $PRERELEASE
  on:
    tags: true
    repo: covfefe-spikes/nodejs-release-spike
  skip_cleanup: true